### ISSUE TITLE
boot runs successful bot no files are written to public

### ISSUE THREAD

**Issue by branch14** [hashobject/perun#101]
I'm trying to get a perun set up. I got to point where it doesn't throw any errors when I run `boot build`, but I does not write any files to `public`, while it claims that it does.

```
[slug] - added slugs to 2 files
[ttr] - added TTR to 2 files
[word-count] - added word-count to 2 files
[permalink] - added permalinks to 2 files
[canonical-url] - added canonical urls to 2 files
[build-date] - added date-build to 2 files
[gravatar] - added gravatar to 2 files
[render] - rendered 2 pages
[collection] - rendered collection index.html
[inject-scripts] - injected 0 scripts into 3 HTML files
[sitemap] - generated sitemap and saved to public/sitemap.xml
```

My build.boot file is

https://gitlab.com/200ok/200ok.gitlab.io/blob/master/build.boot

**Comment by martinklepsch** [comment]
Sorry for brevity but try `boot build target` that will put all files in
Boots fileset into the "target" directory.

**Comment by branch14** [comment]
Thx Martin,

`boot build target` works. It mysteriously writes files to `target/public`.
