### ISSUE TITLE
Pegdown has been deprecated; pick a new markdown parser

### ISSUE THREAD

**Issue by bhagany** [hashobject/perun#126]
I just noticed that Pegdown has been EOL'd as of five days ago (see README: https://github.com/sirthias/pegdown), so I think a replacement is probably worth it for Perun.  I've been toying with the idea of adding Pandoc support, and there are a few other mentions of this in other issues, but I'm not sure if Pandoc can support all of the same features that Pegdown does.  Pegdown's deprecation notice recommends switching to [flexmark-java](https://github.com/vsch/flexmark-java), which is apparently a drop-in replacement.

I can integrate one or both of these, but I'd like to get some opinions on what you'd like to see, whether Pandoc, flexmark-java, some other option, or possibly multiple integrations.  Let me know what you think.

**Comment by podviaznikov** [comment]
@bhagany I don't have any preferences.
It would be nice if new parser also supported anchorlinks for the headers (https://github.com/hashobject/perun/blob/master/src/io/perun/markdown.clj#L22).
It seems that flexmark-java supoports that, so I see no problems for me.

**Comment by bhagany** [comment]
I have a working integration of `flexmark-java` here: https://github.com/bhagany/perun/tree/flexmark-java.  However, it doesn't yet support the `smarts` or `quotes` extensions, so we should probably hold off making the switch until it reaches feature parity.  Once support is added, all it should take is bumping some deps and making sure tests pass.

**Comment by Deraen** [comment]
Looks good. And I don't think there is great hurry to replace Pegdown, so we can easily wait until flexmark adds the last two missing features.

**Comment by bhagany** [comment]
I am deleting my fork, so I moved this branch here: https://github.com/hashobject/perun/tree/flexmark-java

**Comment by bhagany** [comment]
`smarts` and `quotes` are now supported, PR here: https://github.com/hashobject/perun/pull/170
