### ISSUE TITLE
Unable to resolve var: s3-sync in this context

### ISSUE THREAD

**Issue by theronic** [hashobject/perun#127]
I get this error when I use the example code in the README:

```
 ❯ boot dev                                                                                                                                                                                    [12:26:52]
clojure.lang.ExceptionInfo: Unable to resolve var: s3-sync in this context
    data: {:file
           "/var/folders/8j/27sz_2rj0kd1b3v9y4n1_1t00000gn/T/boot.user3794536342121430912.clj",
           :line 19}
java.lang.RuntimeException: Unable to resolve var: s3-sync in this context
```

I checked the version on the s3-sync and it seems to match. Is this a weird Maven thing on my machine?

**Comment by podviaznikov** [comment]
Hey, did you import library properly?
Do you have this line:

https://github.com/podviaznikov/podviaznikov.com/blob/master/build.boot#L6

and this: https://github.com/podviaznikov/podviaznikov.com/blob/master/build.boot#L23
?

**Comment by bhagany** [comment]
If @podviaznikov's advice wasn't the fix you needed, would you mind showing your build.boot?

**Comment by bhagany** [comment]
Hi @pate - I'm going to assume your problem is fixed and close this ticket, but if you're still having trouble, feel free to reopen
