### ISSUE TITLE
Reload browser window on change

### ISSUE THREAD

**Issue by theronic** [hashobject/perun#128]
How can I trigger the browse window to reload whenever the boot watch task reruns?

**Comment by podviaznikov** [comment]
This is a good question. I personally don't know. Maybe someone else have an idea?

**Comment by bhagany** [comment]
I don't really understand the aim of reloading on every watch loop.  boot-reload will trigger a browser refresh when anything relevant changes.  Could you describe your use case if you need more than that?

**Comment by bhagany** [comment]
Hi @pate - if you still need help on this issue, feel free to reopen.

**Comment by theronic** [comment]
Hi @bhagany, boot-reload only works for ClojureScript projects AFAIK.

I want to be able to press save in my editor and see content update immediately on my other monitor for my humble HTML/CSS static site.

**Comment by bhagany** [comment]
Okay, I see.  You have two options that I know of: stick with boot-reload and only load cljs in dev, or take a look at boot-livereload, https://github.com/Deraen/boot-livereload.  I've never used boot-livereload, but I'm pretty sure it's the same idea as boot-reload, except using js instead of cljs.

**Comment by bhagany** [comment]
To be clear, I don't think there's a way to do this without running some script on the client side.

**Comment by theronic** [comment]
Tried getting boot-livereload running. No luck :/

**Comment by bhagany** [comment]
I'd be happy to help, if you could be more specific about the problem
