### ISSUE TITLE
New plugin: meta

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/perun#14]
I want to have plugin where I can specify some global settings that would be accessible to all templates.
E.x. I'm thinking that `base_url`, `site_name`, `copyright_dates` are repetitive and can be used on any page.
Right now there os no way of specifying such options globally for all tasks.

I'm thinking creating super simple task called `meta`. Some thing like this:

```
(comp (meta {:name "Hashobject Blog" :base_url "http://blog.hashobject.com"})
          (markdown)
           (draft)
          ...)

```

Thank this meta can be merge with every file meta, or it can be accessible as `(:global-metadata (meta fileset))`.

**Comment by podviaznikov** [comment]
@martinklepsch, @Deraen let me know what you think about this one

**Comment by Deraen** [comment]
Good idea. Instead of defining the metadata in build.boot, could be useful to read the data from file, then boot doesn't have to be reloaded to see the changes and it would keep build.boot simpler.

**Comment by podviaznikov** [comment]
That is a good point about reloading. Reading from file makes more sense now to me.

**Comment by martinklepsch** [comment]
Yeah. The main.cljs.edn approach in boot-cljs came to mind :)

**Comment by podviaznikov** [comment]
@martinklepsch what do you mean by `main.cljs.edn` approach in boot-cljs? Are you referring to this file https://github.com/adzerk-oss/boot-cljs/blob/0e1dbee515fd7da31950c0de8eab99acddaabbe3/src/adzerk/boot_cljs/middleware.clj#L33?

**Comment by martinklepsch** [comment]
@podviaznikov I was referring to this: https://github.com/adzerk-oss/boot-cljs#multiple-builds
