### ISSUE TITLE
Task inject-scripts fails for boot-cljs output.

### ISSUE THREAD

**Issue by ericcheek** [hashobject/perun#145]
Java's [String.replaceAll](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#replaceAll(java.lang.String,%20java.lang.String)) (used [here](
https://github.com/hashobject/perun/blob/master/src/io/perun/contrib/inject_scripts.clj#L7)) treats '$' signs as regex group match references. Most inputs containing '$' lead to IllegalArgumentExceptions (for example, injecting cljs optimized with the Google Closure Compiler).

**Comment by bhagany** [comment]
Good catch, thank you for the report.  A fix should not be long in coming.
