### ISSUE TITLE
look for metadata with dashes by default

### ISSUE THREAD

**Issue by martinklepsch** [hashobject/perun#17]
Instead of looking for metadata like `date_published` be default it seems more idiomatic to look for `date-published`. As far as I understand both are valid YAML keys.

Happy to create a PR if wanted.

**Comment by podviaznikov** [comment]
I think makes sense to use Clojure convention. @Deraen what do you think should be default?

**Comment by Deraen** [comment]
:+1:

**Comment by martinklepsch** [comment]
Cool. PR incoming.
