### ISSUE TITLE
site-title get's lost in `atom-paths`

### ISSUE THREAD

**Issue by martinklepsch** [hashobject/perun#175]
When the `site-title` is supplied as task option the atom-paths function loses it the moment it uses `grouped-paths`: https://github.com/hashobject/perun/blob/master/src/io/perun.clj#L1022

Merging in `(dissoc options :grouper :sortby :comparator)` here: https://github.com/hashobject/perun/blob/master/src/io/perun.clj#L794-L796 should fix the issue but I'm not sure if thats the right solution.

**Comment by bhagany** [comment]
Sorry about that, I broke this during my recent atom refactor.  We merge task-level metadata like this in a few other places, so I used the same method to fix this bug, for consistency.
