### ISSUE TITLE
re-pattern usage

### ISSUE THREAD

**Issue by martinklepsch** [hashobject/perun#184]
In some places re-pattern is used with strings that represent directories. As long as the directories don't contain any special characters it's fine but if they for example are set  to `"."` unexpected stuff might happen.

```
(let [match-doc-root (re-pattern (str "^" doc-root))]
  (-> path
      (string/replace match-doc-root "")
```

**Comment by bhagany** [comment]
Good point. It should be relatively easy to escape those strings.
