### ISSUE TITLE
Trace conflicts with #'boot.util/trace

### ISSUE THREAD

**Issue by arichiardi** [hashobject/perun#186]
Hello folks!

With the advent of `boot` `2.7.2-SNAPSHOT` a conflict arises:

```
java.lang.IllegalStateException: trace already refers to: #'boot.util/trace in namespace: boot.user
     clojure.lang.ExceptionInfo: trace already refers to: #'boot.util/trace in namespace: boot.user
```

This is because someone (myself) added a new method for logging in boot. I did not expect it would conflict with perun.

I have just tried the blog example and indeed it breaks.

A solution would be not to use `:refer :all` in the `build.boot` file.

**Comment by podviaznikov** [comment]
This seems to be fixed now.

**Comment by mprokopov** [comment]
I still have this issue when try to follow README examples
this build.boot
```
(set-env!
 :source-paths #{"content"}
 :dependencies '[[perun "0.4.2-SNAPSHOT" :scope "test"]
                 [pandeiro/boot-http "0.8.3" :exclusions [org.clojure/clojure]] ])

(require '[io.perun :refer :all]
         '[pandeiro.boot-http :refer [serve]])
```

causes following error

```
java.lang.IllegalStateException: trace already refers to: #'boot.util/trace in namespace: boot.user
clojure.lang.ExceptionInfo: trace already refers to: #'boot.util/trace in namespace: boot.user
```


```
boot -u
Retrieving maven-metadata.xml from https://repo.clojars.org/ (3k)
#http://boot-clj.com
#Wed Nov 29 16:06:35 EET 2017
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.9.0-alpha17
BOOT_VERSION=2.7.2
```

Is there another fix except not to use `:all` in `:refer` ?

**Comment by arichiardi** [comment]
The fix was basically to use an `:as` instead of referring all the symbols. You can also `:rename` but it has to be in your file unless the name changes in perun

**Comment by devurandom** [comment]
Could someone please reopen this report and also fix the readme? I also ran into this.

Note that after changing `:refer :all` to `:as perun`, the `$ boot markdown` command becomes `$ boot perun/markdown`.
