### ISSUE TITLE
Faster recompilation

### ISSUE THREAD

**Issue by Deraen** [hashobject/perun#2]
Currently when using this together with watch task with 20 posts recompilation takes maybe 1.5 seconds. This could probably be made much faster by only parsing the changed md files.

Idea:
- Instead of writing metadata to a file, assoc it to fileset metadata
- Store metadata as a map of md file -> metadata
- Markdown task would check for changed files and update those in the metadata

**Comment by podviaznikov** [comment]
It's and interesting idea to store everything in fileset  metadata.
Are you proposing to get read of `meta.edn` completely?

**Comment by Deraen** [comment]
To get rid of meta.edn. Yes.

But the more important change would be to store metadata in map and parse only changed files. Using fileset metadata is not required for this.

**Comment by podviaznikov** [comment]
And how would you pass that map between boot tasks? You want to have global map accessible from all the tasks?

**Comment by Deraen** [comment]
If I remember correctly, this should work:

``` clj
(boot/with-pre-wrap fileset
  (println (:metadata (meta fileset)))
  (with-meta fileset {:metadata {"/foobar.md" {}}}))
```

**Comment by podviaznikov** [comment]
I think I like that. Never used `meta` before but it's seems like a really good use-case to try.
Let me play with this

**Comment by Deraen** [comment]
Check https://github.com/Deraen/boot-less/blob/master/src/deraen/boot_less.clj#L29-L32 for example how to find which files changed runs.

**Comment by podviaznikov** [comment]
I have PR (https://github.com/hashobject/perun/pull/11) to store all metadata as map md->file metadata (as was suggested).

**Comment by podviaznikov** [comment]
I was thinking about this and now faster recompilations makes more sense. I saw how you are using perun with http-server and livereload and it makes sense that you want faster reloads.
My initial workflow was different and I didn't care about speed before. But I think I like your workflow more. And I like that boot just allows us to chain those tasks together.

**Comment by podviaznikov** [comment]
Fixed in https://github.com/hashobject/perun/pull/15
