### ISSUE TITLE
Upgrade Pegdown to flexmark-java

### ISSUE THREAD

**Issue by NightMachinery** [hashobject/perun#214]
Pegdown is long deprecated:
:>>>[ DEPRECATION NOTE ](https://github.com/sirthias/pegdown)<<<:
Although still one of the most popular Markdown parsing libraries for the JVM, pegdown has reached its end of life.

The project is essentially unmaintained with tickets piling up and crucial bugs not being fixed.
pegdown's parsing performance isn't great. In some cases of pathological input runtime can even become exponential, which means that the parser either appears to "hang" completely or abort processing after a time-out.

Therefore pegdown is not recommended anymore for use in new projects requiring a markdown parser.
Instead I suggest you turn to @vsch's [flexmark-java](https://github.com/vsch/flexmark-java), which appears to be an excellent replacement for these reasons:

Modern parser architecture (based on commonmark-java), designed from the ground up as a pegdown replacement and supporting all its features and extensions
30x better average parsing performance without pathological input cases
Configuration options for a multitude of markdown dialects (CommonMark, pegdown, MultiMarkdown, kramdown and Markdown.pl)
Actively maintained and used as the basis of an IntelliJ plugin with almost 2M downloads per year
The author (@vsch) has actively contributed to pegdown maintenance in the last two years and is intimately familiar with pegdown's internals and quirks.
In case you need support with migrating from pegdown to flexmark-java, @vsch welcomes inquiries in here or here.

**Comment by bhagany** [comment]
This has already been done for some time, check it out: https://github.com/hashobject/perun/blob/master/src/io/perun/markdown.clj

Are we still referencing Pegdown somewhere?

**Comment by allentiak** [comment]
I have checked the code. And no, we don't :-)
