### ISSUE TITLE
[BUG]: Sitemap task in blog example throws error

### ISSUE THREAD

**Issue by jaidetree** [hashobject/perun#221]
There's an issue with the sitemap validator ns hashobject/sitemap#6 preventing the blog example for building.

# REPRODUCTION
1. Clone this repo
2. cd into examples/blog
3. Run boot build

## Expected
- Blog builds successfully

## Actual
An error is thrown due to sitemap.validator's ns failing spec.

## Environment
| Name                       | Value                   |
| -------------------------- | ----------------------- |
| Operating System           | OS X (10.14, Mojave)    |
| Clojure Version            | 1.10                    |
| Leiningen Version          | 2.8.3                   |

## Solution
- Created pull request hashobject/sitemap#7 to remove the unused dep that was failing spec
- Specify new version of sitemap into boot deps once released with fix to validator ns

**Comment by jaidetree** [comment]
Closing this in favor of Clojure 1.9+ support issue #227

**Comment by margaretjoanmiller** [comment]
I'm getting this error again in clojure 1.10.1 despite someone else getting it working on the same version?
