### ISSUE TITLE
Consider moving to flexmark-java

### ISSUE THREAD

**Issue by arichiardi** [hashobject/perun#239]
Hi all!

Given the following [Pegdown Deprecation Note](https://github.com/sirthias/pegdown#-deprecation-note-), maybe `perun` might want to consider moving to `flexmark-java` as suggested there.

I found a couple of problems in my blog that are easily fixable, but `pegdown` is not going to be fixed anymore.

**Comment by allentiak** [comment]
Hmmm...
Doesn't the latest master version already use flexmark-java? (albeit
probably not the latest version)

**Comment by arichiardi** [comment]
Oh sorry, I haven't checked `master`, it would be great to have it in a `-SNAPSHOT` for sure. In the meantime, I will close this issue and thanks!

**Comment by allentiak** [comment]
It's OK :-)
I would only advise you to check 'master' before reporting this kind
of dependency bugs in the future.

**Comment by arichiardi** [comment]
Will definitely do :smile:
