### ISSUE TITLE
Publish perun 0.5.0-alpha-SNAPSHOT

### ISSUE THREAD

**Issue by allentiak** [hashobject/perun#246]
So we can get feedback about the changes since 0.4.x

**Comment by arichiardi** [comment]
This has been done!

https://clojars.org/perun/versions/0.5.0-SNAPSHOT

Now every time we push a git tag to `master` - whether it is `-SNAPSHOT` or not - we will have a new version on Clojars

**Comment by allentiak** [comment]
Thanks, Andrea!

**Comment by podviaznikov** [comment]
amazing!
