### ISSUE TITLE
New plugin: tags

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/perun#27]
I'm thinking about creating tags plugin like this (https://github.com/totocaster/metalsmith-tags).
@martinklepsch, @Deraen do you need tag pages for your blogs, or it's not important right now?

**Comment by martinklepsch** [comment]
I personally don't use tags currently. Would still be a useful addition I guess.

**Comment by Deraen** [comment]
Yeah I would probably use this.

**Comment by Deraen** [comment]
Unless someone else wants to implement this, I can eventually do this.

**Comment by podviaznikov** [comment]
Cool, go ahead:) We have plenty of plugins in the pipeline.

**Comment by Deraen** [comment]
Btw. this might not need as much as a task but just a custom renderer, finding the tags is just one reduce away anyway.

**Comment by rqcy** [comment]
Hi, what's the status of this plugin?

**Comment by Deraen** [comment]
It is relatively easy to list tags using the regular collection task:

https://github.com/Deraen/deraen.github.io/blob/blog/src/blog/views/tags.clj
https://github.com/Deraen/deraen.github.io/blob/blog/build.boot#L49
