### ISSUE TITLE
Reload blog specific Clojure code

### ISSUE THREAD

**Issue by Deraen** [hashobject/perun#3]
If I change e.g. post or collection render function I have to restart boot to see the changes. I can think of two alternatives to make this work with watch task so that the changes are picked up instantly.
1. A task witch uses clojure.tools.namespaces refresh
2. render and collection tasks are instead run inside a new pod each time

I would probably prefer the second option. It should be quite fast when used with pod pool.

**Comment by podviaznikov** [comment]
Thanks for the idea. Let me read about pods more.
