### ISSUE TITLE
Split render tasks in two

### ISSUE THREAD

**Issue by Deraen** [hashobject/perun#30]
The `render` and `collection` task implementations could be split into `render-hiccup`, `collection-hiccup` and `write-html` tasks I think.

A use case would be to do some transformations to hiccup in between:

``` clojure
(comp (render-hiccup :rendered 'foobar/post)
      (highlight)
      (write-html :out "public/post/foobar.html"))
```

`render` and `collection` could still work as is, they would just combine two other tasks:

``` clojure
(deftask render [...]
  (comp (render-hiccup :rendered renderer) (write-html :out ...)))
```

I could implement this when I have need for this. For now I'm using Highlight.js.

**Comment by podviaznikov** [comment]
Interesting. This might be useful if we have `highlight` task.
What else can be done after html rendering? Validation, but I don't think people doing it those days?

**Comment by Deraen** [comment]
Hyphenation would be another transformation I would use if available. I'm not sure if it should be done to  the hiccup or to markdown content directly.

**Comment by podviaznikov** [comment]
Interesting, never heard of `hyphenation` before. Is anyone doing it? How does it work?

**Comment by Deraen** [comment]
https://github.com/mnater/hyphenator is probably one of the more used libs. I'm working on clojure port.

**Comment by Deraen** [comment]
Lets see what highlight or hyphenate tasks require before changing how render works.

**Comment by martinklepsch** [comment]
Technically the `render` and `collection` tasks are no coupled to hiccup right? They could use any kind of templating thing theoretically. I think not imposing anything here is a good thing.

For post processing like hyphenation/highlighting html strings could be easily converted into more ergonomic data structures as part of the (.e.g. hyphenation) task.

**Comment by podviaznikov** [comment]
@Deraen what is your current opinion on this? You have `hyphenation` task that is working over existing html files. Maybe that is the way to go, create tasks that postprocess final HTML files?

**Comment by Deraen** [comment]
Yeah currently it looks like postprocessing html files is the way.
