### ISSUE TITLE
New plugin: highlight code

### ISSUE THREAD

**Issue by Deraen** [hashobject/perun#32]
Might require splitting the render if half so hiccup can be modified. Or could maybe work on existing html. (#30).

But first we need highlighting lib usable from Boot. There doesn't seem to be any maintained Java implementations. [Jygments](https://github.com/tliron/jygments) looks the most useful but it is not released on maven.

Instead we could use a pod with Jython and use Pygments (a python lib). Example https://github.com/tailrecursion/boot-hoplon/blob/master/src/tailrecursion/boot_hoplon/pygments.clj.

**Comment by podviaznikov** [comment]
I used to have library (https://github.com/hashobject/pygmenter. ) which is very similar to code from `https://github.com/tailrecursion/boot-hoplon/blob/master/src/tailrecursion/boot_hoplon/pygments.clj`.
But example from tailrecursion has more options (and I didn't maintained mine version much).

I agree that having nice highlighting library is good. Also agree that highlight plugin would be very useful.
