### ISSUE TITLE
Support strikethroughs

### ISSUE THREAD

**Issue by Deraen** [hashobject/perun#46]
**Waiting for** theJohnnyBrown/endophile#8

**Comment by martinklepsch** [comment]
This still waiting for a release or is it included in `[endophile "0.2.0-SNAPSHOT"]`?

**Comment by Deraen** [comment]
It's included in `0.2.0-SNAPSHOT` but such version is not yet pushed to clojars.

**Comment by Deraen** [comment]
Works now that we are using latest Pegdown directly.
