### ISSUE TITLE
Allow markdown task to use an external markdown parser

### ISSUE THREAD

**Issue by greywolve** [hashobject/perun#48]
I've added this in a fork over [here](https://github.com/greywolve/perun/blob/master/src/io/perun.clj#L36). I wanted this so I could use [Pandoc](http://www.pandoc.org) instead of Endophile for markdown parsing. Would you be interested in supporting this ? 

``` clj
;; argument is an edn vector of strings
(markdown :cmd ["pandoc"])
```

Thanks for the library by the way, really cool idea.

**Comment by Deraen** [comment]
This is definitively an interesting idea. Pandoc can also do code highlighting (#32).

I wonder if an separate task and maybe library would be good idea for this?

Separate task might be good choice as it would be useful to define option for Pandoc and we probably don't want to make markdown task too complicated.

**Comment by greywolve** [comment]
I was going to make an isolated task, but then I realized it would be basically reusing all the same code that already exists, barring a few small changes. Though you are probably right, it makes more sense as a separate task. I'd be happy to make one (though there will be a fair bit of duplication).

**Comment by Deraen** [comment]
Once it's separated as a task we could probably move the shared logic to functions.

**Comment by Deraen** [comment]
Might also be useful to create Clojure wrapper for Pandoc, like: https://github.com/pvorb/scala-pandoc

Mostly it would just translate given options to cli arguments, and take care of calling the command properly.

**Comment by greywolve** [comment]
Great idea. :) I'll get onto this.

**Comment by Deraen** [comment]
And note about using `conch`, you shouldn't add transitive dependencies to the perun and instead you should add the dependencies to just the pods.

But as it happens, boot is already using `conch`: https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/from/me/raynes/conch.clj so you can use `boot.from.me.raynes.conch` ns in your code without adding any dependencies.

... Though if Pandoc wrapper is created, that's what would be using Conch and it would be used through a pod.

**Comment by greywolve** [comment]
Ahh, I knew boot was using `conch` but wasn't aware they actually had it copied to a namespace inside boot, good to know!

**Comment by podviaznikov** [comment]
@greywolve it's a great idea to add pandoc support. I think it would be useful.
I usually check metalsmith for the inspirations (http://www.metalsmith.io/), they also have `pandoc` as separate task with task specific options: https://github.com/arve0/metalsmith-pandoc.
So I also agree with @Deraen suggestion to make separate task.

**Comment by Deraen** [comment]
Would be cool if Pandoc support could be implemented using shared library (https://github.com/ShabbyX/libpandoc) and JNA. Then users wouldn't even need to install the binary.

Unfortunately it looks to be really hard to build libpandoc because Haskell dependency hell.

**Comment by martinklepsch** [comment]
I think this would be really cool. Pandoc seems very comprehensive and the speed pegdown is moving at is a blocking factor for me right now.

**Comment by podviaznikov** [comment]
@greywolve I think I would be interested in the pandoc support.
I think I agree with your proposed syntax: `(markdown :cmd ["pandoc"])`.
I like idea of having one task which can call different implementations based on arguments.
I tried to explore similar idea for html renderers https://github.com/hashobject/perun/pull/40/files

**Comment by Deraen** [comment]
I think tasks should be kept simple and they only do one thing. If there is need for alternative markdown or render implementations, they could be provided as separate tasks.

**Comment by allentiak** [comment]
Given that #173 has been merged...
Should we close this?

**Comment by allentiak** [comment]
Closed.
