### ISSUE TITLE
New plugin: Asciidoctor

### ISSUE THREAD

**Issue by nicorikken** [hashobject/perun#49]
I'm working on an Asciidoc parser using [Asciidoctor](http://asciidoctor.org/). The Ruby commands are run in [boot-jruby](https://github.com/tobias/boot-jruby). As it is being used for documentation, the intention is to use the diagram back-end for generating PlantUML and Graphviz images to be included in the final doc. Generating pdf versions on the side would be another option, but in my opinion this goes beyond the goals of Perun.

I have a couple of points worth discussing:
1. One of our current documents has too many characters to be handled in the eval statement when handling pods (concerning the render stage currently). I'm considering a file-based solution for HTML inclusion. So the Asciidoctor plugin would generate a (partial) HTML file and adds the referred filename in say a :include key in the metadata. This allows pages to refer to this file, rather than load the value from the :content key. This slurp could also be handled within the Asciidoctor plugin to end up with a similar behavior as say the Markdown plugin.
2. Asciidoc offers several built-in attributes to handle metadata. I plan on parsing the Asciidoc file to extract these attributes and include these into the metadata to be reference.
3. Asciidoc offers the ability to evaluate the file for different inline inclusion macros. My use-case uses these ifdef statements to include code examples for different languages. We intend to generate the document for these different attributes. This evaluation could be done by parsing all ifdef commands and just evaluating all options. A more conservative way would be to either include the attributes in the plugin call, and/or announcing the desired evaluation attributes in a commented asciidoc file header.

**Comment by podviaznikov** [comment]
@nicorikken having Asciidoctor pluging would be great.
Also in my opinion generating pdfs or ebooks can totally be Perun plugins at some point. 

Regarding your questions/points:
1. is it know issue with boot (too many characters eval in the pod)? 
2. sounds good. I think it's reasonable. what kinda of metadata would be added
3. didn't quite understand problem, question. Maybe you can provide more context

**Comment by nicorikken** [comment]
@podviaznikov I assume pdf and epub generation would be based on the final rendering stage, after the rendering stage has been handled.
1. Not that I know of, but in the Boot documentation it focuses mainly on using the filesets for transferring content. Are you hinting at finding a workaround within Boot? Edit: The fileset metadata is limited in size, and therefore the max number of character is limited.
2. This mainly concerns metadata present in current examples, like author, title, version, date, etc.
3. I guess I'll just work out a generic way of handling different version (with the majority of the content identical). I'm thinking about having some options available for which to evaluate (say three different language versions from the same source-document). But in a way the multiple versions of the final content would have to be associated with the same original source-file.

**Comment by podviaznikov** [comment]
@nicorikken:
1. interesting I didn't know that fileset metadata is limited. If it's indeed the problem we would need global solution. It works for me now with 20 blog posts. Do you know what is the limit? @Deraen, @martinklepsch do you know about such limitation?
2. nice, your initial plan sounds right here
3. sounds like you have a plan:)

**Comment by ekroon** [comment]
@podviaznikov 

The problem with storing output in the metadata is that there is a limitation to what you can store in a string in a .class format (65535 bytes). If you start a boot repl the following shows the problem:

``` clojure
(boot.pod/with-eval-in (boot.pod/make-pod) (pr-str ~(reduce str (take 65535 (repeat "s"))))) 
```

versus

``` clojure
(boot.pod/with-eval-in (boot.pod/make-pod) (pr-str ~(reduce str (take 65536 (repeat "s"))))) 
```

which yields

```
clojure.lang.Compiler$CompilerException: java.lang.ClassFormatError: Unknown constant tag 115 in class file pod$eval234, compiling:(NO_SOURCE_PATH:0:0)
             java.lang.ClassFormatError: Unknown constant tag 115 in class file pod$eval234
```

So doing something extra with the output after a markdown / asciidoctor generation step can be problematic. A large amount of files to transform will not trigger this problem, but a large input file will. :)

**Comment by martinklepsch** [comment]
I had a brief chat with @micha about this and he mentioned that the [implementation](https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/pod.clj#L211) of `eval-in*` might be the culprit here. Switching from something like `pr-str` to a streaming protocol like Fressian for this stuff should allow for bigger things to be passed into pods.

**Comment by ekroon** [comment]
A bit more investigation indicates that the problem is probably in the combination of `eval` and `backtick\template` as [with-eval-in](https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/pod.clj#L220) has the same problem:

``` clojure
(boot.pod/with-eval-in false (identity ~(reduce str (take 65536 (repeat "s")))))
```

Maybe some kind of helper function to split long strings in chunks is a solution?

**Comment by nicorikken** [comment]
I've managed to get a workaround via files, allowing longer strings of generated html content. I've now implemented this using an AbsoluteFilePath of the output files to an `:include` key. I was considering adding some options to bring backwards compatibility with the `:content` based approach, although it might make more sense to adopt a file-based solution as default to avoid running into the issues mentioned above.

**Comment by podviaznikov** [comment]
@nicorikken do you have code I can look into?

**Comment by dl1ely** [comment]
Guys, i would love to see a asciidoctor-plugin. Anything i can help with? @nicorikken can you do a PR soonish?

**Comment by nicorikken** [comment]
I'm currently working on making a clean pull request from the current working state. Compatibility with other Perun features is left to be desired (due to the file-based handling), and dependencies can be reduced by wrapping the handling in a pod (which I lacked to do). In the meantime check my personal clone to watch the progress.

**Comment by nicorikken** [comment]
Now that was relatively easy. I now have a working version. The file-based method lacks compatibility with the other methods used in the Perun base. And of course many features can be added to better suit the Asciidoctor use-case. But still there is a working prototype: https://github.com/nicorikken/perun

**Comment by martinklepsch** [comment]
@nicorikken have you looked at this again since `send!` has been introduced? `send!` is experimental but I think it might solve the issue you were encountering.

https://github.com/boot-clj/boot/issues/339

**Comment by nicorikken** [comment]
@martinklepsch I haven't looked this problem in a while, but that feature seems to fix the problem. I just published my in-house work on the Perun project in a [separate repo](https://github.com/mpare-net/adoc-builder). Still a bit rough though. The `send!` feature seems to be the right way of addressing the issue of passing around large lumps of text, so that would seem a worthwhile improvement on the Perun codebase. Maybe I'll have a go at it at some point.

**Comment by nicorikken** [comment]
I'm currently prototyping Asciidoctorj in Clojure. If I get the desired features to work, I want to redo my original PR. I'll probably consider the send implementation a secondary step, as this is equally an issue for the Markdown handling. It is just that my use-case involves large documents.

**Comment by nicorikken** [comment]
I've been able to get nice HTML out of the Asciidoctorj using Clojure. I initially started creating an asciidoctor-clj wrapper around basic Java interop to hopefully support re-use. But that led to a procrastination on function structure. Realizing it was going nowhere, I let it be and decided to stick with plain Asciidoctor for the time being. My [Asciidoctor by makefile Github pages repo](https://github.com/nicorikken/nicorikken.github.io) is online if somebody is interested. Conclusion: typing indexes and feeds by hand is boring and not very dynamic. So back to square one: Perun! (a colleague of mine is contributing to [Cryogen](https://github.com/cryogen-project/cryogen) but I like the Perun structure better.

Having become more experienced with Clojure, I know understand how the `send!` command is supposed to be used. Rather than writing an `asciidoctor-clj` library first, I'll be making an Asciidoctor task for Perun first, and maybe later extract a relevant abstraction into a separate project for reuse.

One issue I'm struggling with in my mind, is how to bring the resulting HTML structure of the Markdown and Asciidoctor content close to each other. Because if the structure is different, themese would ideally support both. Or if themes are targeted to a certain output format (like the couple of [Asciidoctor stylesheets](https://github.com/mpare-net/asciidoctor-stylesheet-factory)), the ideally it should be easy to convert the Markdown to Asciidoctor style, or the other way around. That could of course be 2 tasks corresponding to each transformation. Anyway, that's for future issues.

**Comment by martinklepsch** [comment]
I'd suggest that for a first version it's not very important to make
different markup formats play nice together - in practice I would expect
most people to use mostly one anyways.

**Comment by nicorikken** [comment]
I was having trouble getting the final rendering to work (somehow), but the task itself seems to work now. Once I get the rendering to work, I can better review the behavior of the task, to see how it fits in with the Markdown behavior. I've created a PR https://github.com/hashobject/perun/pull/100 for the current version.

**Comment by nicorikken** [comment]
I got the rendering to work now. Mostly because I got all the source and resource directories mixed up and had some issues with my dependencies. Anyway, it sort-of works now.

_Frontmatter_
The AsciidoctorJ seems to have issues with the YAML `frontmatter` despite the fact that Asciidoctor should be able to [ignore such front-matter](http://asciidoctor.org/docs/user-manual/#front-matter-added-for-static-site-generators) out of the box. Maybe it is a config issue. For now the `io.perun.markdown/remove-metadata` would do the job nicely.

_Title_
Also the title is not included in the resulting output. If I render the Markdown, it does include a `<h1>` for the main title (`# Title`) but not so for the Asciidoctor content.

I assume both can be fixed using some AsciidoctorJ configuration parameters. I'll look into that later on.

**Comment by nicorikken** [comment]
Metadata support is proposed: https://github.com/hashobject/perun/pull/191
And I started working on asciidoctor-diagram image generation as well.

**Comment by nicorikken** [comment]
I got image generation working again, not inline though, so I'll have to manage files. I did get a win with including coderay syntax highlighting. It requires the attribute to be set on the conversion command, and the attribute being set in the file is not enough. So probably I have to extract the attributes first, and then feed them into the final conversion step. Something to work out in further detail for good ergonomics.

**Comment by nicorikken** [comment]
https://github.com/hashobject/perun/pull/194 🎉

**Comment by allentiak** [comment]
@nicorikken Just curious...  Hasn't this been superseded by #183?

**Comment by allentiak** [comment]
Yes, it has.
