### ISSUE TITLE
Task for rendering static pages

### ISSUE THREAD

**Issue by martinklepsch** [hashobject/perun#55]
I'm currently doing something like this:

``` clojure
(p/collection :renderer 'org.martinklepsch.blog/error-page :page "error.html")
```

but dropping any of the passed arguments, i.e. generating a truly static html file: 

``` clojure
(defn error-page [_ _]
  (base ...))
```

While using the collection task works perfectly well in this case it might make sense to provide a general task for this usecase. Potentially task options could be used to pass arguments to the render-fn.

**Comment by podviaznikov** [comment]
@martinklepsch I do the same thing as you: https://github.com/hashobject/perun.io/blob/master/build.boot#L29.
But don't you still want to pass global-metadata in most cases? E.x. to print site name.

My only confusion about using `collection` task for static pages is just name of the task.

Maybe another solution would be to check if `renderer` has parameters or not and than call it in the correct way https://github.com/hashobject/perun/blob/master/src/io/perun.clj#L291.

**Comment by MartyGentillon** [comment]
I am thinking about putting together something that should allow you to render html fragments into templates.
