### ISSUE TITLE
Key metadata by path instead of filename

### ISSUE THREAD

**Issue by martinklepsch** [hashobject/perun#56]
Metadata in perun should be keyed by the path relative to the fileset instead of filenames. Plain filenames can be overriden by files with the same name.

I'm also thinking of redundantly adding the path to the metadata map which would easily allow filtering and grouping by path without having to deal with MapEntries all the time.

**Comment by martinklepsch** [comment]
Also adding the `:path` to the map would allow to easily construct a perun metadata map from a list of maps.

**Comment by Deraen** [comment]
:+1:

**Comment by podviaznikov** [comment]
@martinklepsch your PR is merged now. Do we want to do something else in the scope of this issue? Do we want to remove `:filename` field completely from the code?

**Comment by martinklepsch** [comment]
I think it's fine as is. File name might still be useful in some cases.
