### ISSUE TITLE
Pagination task

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/perun#63]
@martinklepsch I think we can extract your pagination task(https://github.com/martinklepsch/martinklepsch.org/blob/master/build.boot) and put it into perun. What do you think?

**Comment by martinklepsch** [comment]
Sounds good. I was also wondering if we should setup a contrib namespace or
a wiki page or something else where where we can collect perun related
tasks by others.

**Comment by Deraen** [comment]
There's a list in README: https://github.com/hashobject/perun#3rd-party-useful-plugins

**Comment by podviaznikov** [comment]
Yes, we had that section on README for some time now. I moved it to the top of the page yesterday, so people can see it better now.
I think it is much better way to move forward with creating separate projects for plugins/tasks and just referencing them in the wiki. I'd like perun to be small (with some default batteries) and extendable.
