### ISSUE TITLE
Image meta plugin

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/perun#66]
Inspired by https://github.com/Jack000/Expose/blob/master/expose.sh I'd like to add `image-meta` plugin that will attach following metadata to the images:
1) several common colors in the image
2) width
3) height
4) filetype

**Comment by podviaznikov** [comment]
@martinklepsch, @Deraen what do you think about this one?
I think https://github.com/Jack000/Expose has few cool things/ideas I'd like to include into perun (or separate perun task)

**Comment by Deraen** [comment]
:+1:

**Comment by martinklepsch** [comment]
I like the idea too but it seems specific enough to be in a separate
task/project.

**Comment by podviaznikov** [comment]
@martinklepsch I agree that it should be separate task in the separate project.

However I created new PR with the implementation in the current project. My motivations:
1. it's temporary and I would want to move out some tasks out of perun into separate projects when perun becomes a little bit more stable. Right now it's active development phase and it's _easier for me_ to see all tasks and run all of them on my examples and test
2. arguably it would be easier to get review if this task is here (at least for now)
3. again this task is very different from other tasks and it's good to see it in the code to understand the bigger picture: perun can be used not only for blogs generation. Basically after adding this tasks I needed to make small changes in other tasks since perun wasn't flexible enough

Does that make sense? Again, this is definitely temporary. Ideally my goal is to have somethings similar to http://www.metalsmith.io/ with small core and everything else in the separate projects, but we'll see how that will work.

**Comment by martinklepsch** [comment]
Makes total sense, I'd suggest adding `io.perun.contrib.*` namespaces that can contain custom contributed tasks that can be moved to standalone projects later. This way it's clear what can be expected to remain part of the core library.

**Comment by podviaznikov** [comment]
Closing. See https://github.com/hashobject/perun/pull/68
