### ISSUE TITLE
Collection task should work even if no :content files are found

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/perun#77]
E.x. https://github.com/hashobject/perun.io/blob/master/build.boot#L32 this should work without creation of fake `index.md`

**Comment by martinklepsch** [comment]
I'm thinking the same should be true for the render task. If the user only wants to render files that contain a `:content` key they may use the `filterer` option. Hardcoded filtering like this makes it harder to use the render task to render files other than markdown. (i.e. `edn`)

**Comment by podviaznikov** [comment]
Here is the problem when there are not metadata files at all and I want to render one page. And I would want probably to use collection for that.

E.x. I wanted to create static site for perun and collection didn't work because I didn't have any initial files that should be parsed and added to the meta

**Comment by bhagany** [comment]
`collection` now works without any input files present, as of https://github.com/hashobject/perun/commit/341ed5c54552608144cbb9b364253639874d8b07
