### ISSUE TITLE
Add perun to The Clojure Toolbox

### ISSUE THREAD

**Issue by vibl** [hashobject/perun#78]
I'm just discovering perun and I noticed it's not included in The Clojure Toolbox (http://www.clojure-toolbox.com/). It definitely should be!

I have now idea how to submit it to James Reeves though. Maybe a PR to https://github.com/weavejester/clojure-toolbox.com?

Vianney

**Comment by podviaznikov** [comment]
@vibl thanks for your comment. Appreciate it. Feel free to submit it clojure-toolbox. It seems that PR is the right way

**Comment by podviaznikov** [comment]
submitted PR https://github.com/weavejester/clojure-toolbox.com/pull/152
