### ISSUE TITLE
Parse markdown metadata specified in Jekyll style

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/perun#8]
See http://jekyllrb.com/docs/frontmatter/

**Comment by podviaznikov** [comment]
Would be easier when if this task is done: https://github.com/yogthos/markdown-clj/issues/46

**Comment by podviaznikov** [comment]
@martinklepsch this is now in master. So you should switch to YAML metadata now.

**Comment by martinklepsch** [comment]
Great! Nice work!
