### ISSUE TITLE
Specify dedicated location for input files

### ISSUE THREAD

**Issue by jeluard** [hashobject/perun#96]
All files located in folders defined as `:resources` will be candidates for the perun tasks. Is there a way to specify a dedicated location/fileset that will be available to perun tasks only?

**Comment by martinklepsch** [comment]
@jeluard there's no way to do this currently. Could you give a bit more context about your situation/why you're looking for something like this?

**Comment by jeluard** [comment]
I am interested in using `perun` to generate technical documentation for some projects. There might be a bunch of unrelated files in `resources` that should be ignored by perun tasks. Similarly other tasks relying on `resources` might be poluted by those doc files.

**Comment by martinklepsch** [comment]
@jeluard usually `render`, `collection` and many other tasks have a `filterer` option that can be any function receiving the perun metadata of a file. You can use this metadata to only operate on files in a certain directory for example. 

Are you planning to emit the generated documentation into `resources`? Personally I usually try to avoid mixing input/output files inside a projects top level directory. This way you ensure the inputs to your program will always be "clean".

Does this solve your problem? If not also consider the `#perun` channel in Slack for lower latency :)

**Comment by jeluard** [comment]
Right `filterer` is probably good enough for this use case. My second point was related to other tasks seeing docs files even so they are irrelevant. Not sure it's a real problem so I'll just ignore that for now.

Sorry I will use slack next time ;)

**Comment by martinklepsch** [comment]
@jeluard here is totally fine too, no worries 👍 

Depending on when "the other tasks" occur in the pipeline `sift` might just be enough to remove the docs related files from the fileset? Depends a lot on how/when you run things I guess.

**Comment by jeluard** [comment]
Yes sounds like filterer/sift is a great combo here! Thanks
